# Containerized MediaWiki.
# After 'docker-compose up' your wiki will be available at:
# 'https://localhost/wiki'
version: '2'
services:

  nginx:
      restart: always
      image: nginx
      volumes:
        - sites:/data/sites
        - ./custom_cfg/nginx/mediawiki.template:/etc/nginx/conf.d/mediawiki.template
        - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
        - ./custom_cfg/nginx/nginx.key:/etc/nginx/ssl/nginx.key
        - ./custom_cfg/nginx/nginx.crt:/etc/nginx/ssl/nginx.crt
      ports:
        - 80:80
        - 443:443
      environment:
        - SERVER_NAME=localhost
        - http_proxy
        - https_proxy
      entrypoint: /docker-entrypoint.sh
      links:
        - mediawiki
        - parsoid

  mediawiki:
    restart: always
    build:
      context: ./mediawiki
      args:
        - MEDIAWIKI_VERSION=REL1_29  # MediaWiki branch name on GitHub
        - http_proxy
        - https_proxy
    links:
      - mysql
      - parsoid
    depends_on:
      - mysql
      - parsoid
    volumes:
      - sites:/data/sites
      - ./custom_cfg/mediawiki:/conf
    environment:
      - MEDIAWIKI_SITE_SERVER=https://localhost
      - MEDIAWIKI_SITE_NAME=Wiki
      - MEDIAWIKI_SITE_LANG=en
      - MEDIAWIKI_ADMIN_USER=admin
      - MEDIAWIKI_ADMIN_PASS=adminpass
      - MEDIAWIKI_UPDATE=true
      - MEDIAWIKI_DB_HOST=mysql
      - MEDIAWIKI_DB_PASSWORD=rootpass
      - http_proxy
      - https_proxy

  parsoid:
    restart: always
    build:
      context: ./parsoid
      args:
        - http_proxy
        - https_proxy
    volumes:
      - ./custom_cfg/parsoid/config.yaml:/etc/mediawiki/parsoid/config.yaml
    environment:
      - http_proxy
      - https_proxy

  mysql:
    restart: always
    image: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass  # same as MEDIAWIKI_DB_PASSWORD
      - SERVICE_NAME=mysql
      - http_proxy
      - https_proxy

volumes:
  sites:
    driver: local
  dbdata:
    driver: local
